package com.example.aadharscanner.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ADD_MEMBER_AADHAR_DETAIL".
*/
public class AddMemberAadharDetailDao extends AbstractDao<AddMemberAadharDetail, Void> {

    public static final String TABLENAME = "ADD_MEMBER_AADHAR_DETAIL";

    /**
     * Properties of entity AddMemberAadharDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UidNumber = new Property(0, String.class, "uidNumber", false, "UID_NUMBER");
    }


    public AddMemberAadharDetailDao(DaoConfig config) {
        super(config);
    }
    
    public AddMemberAadharDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ADD_MEMBER_AADHAR_DETAIL\" (" + //
                "\"UID_NUMBER\" TEXT);"); // 0: uidNumber
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ADD_MEMBER_AADHAR_DETAIL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AddMemberAadharDetail entity) {
        stmt.clearBindings();
 
        String uidNumber = entity.getUidNumber();
        if (uidNumber != null) {
            stmt.bindString(1, uidNumber);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AddMemberAadharDetail entity) {
        stmt.clearBindings();
 
        String uidNumber = entity.getUidNumber();
        if (uidNumber != null) {
            stmt.bindString(1, uidNumber);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public AddMemberAadharDetail readEntity(Cursor cursor, int offset) {
        AddMemberAadharDetail entity = new AddMemberAadharDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // uidNumber
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AddMemberAadharDetail entity, int offset) {
        entity.setUidNumber(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(AddMemberAadharDetail entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(AddMemberAadharDetail entity) {
        return null;
    }

    @Override
    public boolean hasKey(AddMemberAadharDetail entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
