package com.example.aadharscanner.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHANGE_DESIGNATION_SYNC_DATA".
*/
public class ChangeDesignationSyncDataDao extends AbstractDao<ChangeDesignationSyncData, Long> {

    public static final String TABLENAME = "CHANGE_DESIGNATION_SYNC_DATA";

    /**
     * Properties of entity ChangeDesignationSyncData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EnityCode = new Property(1, String.class, "enityCode", false, "ENITY_CODE");
        public final static Property ShgCode = new Property(2, String.class, "shgCode", false, "SHG_CODE");
        public final static Property MemberCode = new Property(3, String.class, "memberCode", false, "MEMBER_CODE");
        public final static Property UpdatedDesignation = new Property(4, String.class, "updatedDesignation", false, "UPDATED_DESIGNATION");
        public final static Property SyncStatus = new Property(5, String.class, "syncStatus", false, "SYNC_STATUS");
    }


    public ChangeDesignationSyncDataDao(DaoConfig config) {
        super(config);
    }
    
    public ChangeDesignationSyncDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHANGE_DESIGNATION_SYNC_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ENITY_CODE\" TEXT," + // 1: enityCode
                "\"SHG_CODE\" TEXT," + // 2: shgCode
                "\"MEMBER_CODE\" TEXT," + // 3: memberCode
                "\"UPDATED_DESIGNATION\" TEXT," + // 4: updatedDesignation
                "\"SYNC_STATUS\" TEXT);"); // 5: syncStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHANGE_DESIGNATION_SYNC_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChangeDesignationSyncData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String enityCode = entity.getEnityCode();
        if (enityCode != null) {
            stmt.bindString(2, enityCode);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(3, shgCode);
        }
 
        String memberCode = entity.getMemberCode();
        if (memberCode != null) {
            stmt.bindString(4, memberCode);
        }
 
        String updatedDesignation = entity.getUpdatedDesignation();
        if (updatedDesignation != null) {
            stmt.bindString(5, updatedDesignation);
        }
 
        String syncStatus = entity.getSyncStatus();
        if (syncStatus != null) {
            stmt.bindString(6, syncStatus);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChangeDesignationSyncData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String enityCode = entity.getEnityCode();
        if (enityCode != null) {
            stmt.bindString(2, enityCode);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(3, shgCode);
        }
 
        String memberCode = entity.getMemberCode();
        if (memberCode != null) {
            stmt.bindString(4, memberCode);
        }
 
        String updatedDesignation = entity.getUpdatedDesignation();
        if (updatedDesignation != null) {
            stmt.bindString(5, updatedDesignation);
        }
 
        String syncStatus = entity.getSyncStatus();
        if (syncStatus != null) {
            stmt.bindString(6, syncStatus);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ChangeDesignationSyncData readEntity(Cursor cursor, int offset) {
        ChangeDesignationSyncData entity = new ChangeDesignationSyncData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // enityCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // shgCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // memberCode
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // updatedDesignation
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // syncStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChangeDesignationSyncData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEnityCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShgCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMemberCode(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUpdatedDesignation(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSyncStatus(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ChangeDesignationSyncData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ChangeDesignationSyncData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChangeDesignationSyncData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
