package com.example.aadharscanner.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 23): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 23;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        AadharDetailSyncDataDao.createTable(db, ifNotExists);
        AccountDetailSyncDataDao.createTable(db, ifNotExists);
        AddMemberAadharDetailDao.createTable(db, ifNotExists);
        BankBranchDetailDataDao.createTable(db, ifNotExists);
        BankDetailDataDao.createTable(db, ifNotExists);
        BankTypeDao.createTable(db, ifNotExists);
        BlockDaoDataDao.createTable(db, ifNotExists);
        ChangeDesignationSyncDataDao.createTable(db, ifNotExists);
        GpsDataDao.createTable(db, ifNotExists);
        InactiveReasonsDao.createTable(db, ifNotExists);
        KycDocDataDao.createTable(db, ifNotExists);
        KycDocSyncDataDao.createTable(db, ifNotExists);
        LoginInfoDataDao.createTable(db, ifNotExists);
        MemberInactiveReasonDataDao.createTable(db, ifNotExists);
        MemberLoanStatusDataDao.createTable(db, ifNotExists);
        ShgDetailDataDao.createTable(db, ifNotExists);
        ShgInactivationSyncDataDao.createTable(db, ifNotExists);
        ShgInActivSyncDataDao.createTable(db, ifNotExists);
        ShgLoanStatusDataDao.createTable(db, ifNotExists);
        ShgMemberDetailsDataDao.createTable(db, ifNotExists);
        ShgMemberRegistrationSyncDataDao.createTable(db, ifNotExists);
        UpdatedDesignationDao.createTable(db, ifNotExists);
        VillageDataDao.createTable(db, ifNotExists);
        WebRequestDataDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        AadharDetailSyncDataDao.dropTable(db, ifExists);
        AccountDetailSyncDataDao.dropTable(db, ifExists);
        AddMemberAadharDetailDao.dropTable(db, ifExists);
        BankBranchDetailDataDao.dropTable(db, ifExists);
        BankDetailDataDao.dropTable(db, ifExists);
        BankTypeDao.dropTable(db, ifExists);
        BlockDaoDataDao.dropTable(db, ifExists);
        ChangeDesignationSyncDataDao.dropTable(db, ifExists);
        GpsDataDao.dropTable(db, ifExists);
        InactiveReasonsDao.dropTable(db, ifExists);
        KycDocDataDao.dropTable(db, ifExists);
        KycDocSyncDataDao.dropTable(db, ifExists);
        LoginInfoDataDao.dropTable(db, ifExists);
        MemberInactiveReasonDataDao.dropTable(db, ifExists);
        MemberLoanStatusDataDao.dropTable(db, ifExists);
        ShgDetailDataDao.dropTable(db, ifExists);
        ShgInactivationSyncDataDao.dropTable(db, ifExists);
        ShgInActivSyncDataDao.dropTable(db, ifExists);
        ShgLoanStatusDataDao.dropTable(db, ifExists);
        ShgMemberDetailsDataDao.dropTable(db, ifExists);
        ShgMemberRegistrationSyncDataDao.dropTable(db, ifExists);
        UpdatedDesignationDao.dropTable(db, ifExists);
        VillageDataDao.dropTable(db, ifExists);
        WebRequestDataDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AadharDetailSyncDataDao.class);
        registerDaoClass(AccountDetailSyncDataDao.class);
        registerDaoClass(AddMemberAadharDetailDao.class);
        registerDaoClass(BankBranchDetailDataDao.class);
        registerDaoClass(BankDetailDataDao.class);
        registerDaoClass(BankTypeDao.class);
        registerDaoClass(BlockDaoDataDao.class);
        registerDaoClass(ChangeDesignationSyncDataDao.class);
        registerDaoClass(GpsDataDao.class);
        registerDaoClass(InactiveReasonsDao.class);
        registerDaoClass(KycDocDataDao.class);
        registerDaoClass(KycDocSyncDataDao.class);
        registerDaoClass(LoginInfoDataDao.class);
        registerDaoClass(MemberInactiveReasonDataDao.class);
        registerDaoClass(MemberLoanStatusDataDao.class);
        registerDaoClass(ShgDetailDataDao.class);
        registerDaoClass(ShgInactivationSyncDataDao.class);
        registerDaoClass(ShgInActivSyncDataDao.class);
        registerDaoClass(ShgLoanStatusDataDao.class);
        registerDaoClass(ShgMemberDetailsDataDao.class);
        registerDaoClass(ShgMemberRegistrationSyncDataDao.class);
        registerDaoClass(UpdatedDesignationDao.class);
        registerDaoClass(VillageDataDao.class);
        registerDaoClass(WebRequestDataDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
