package com.example.aadharscanner.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.aadharscanner.database.AadharDetailSyncData;
import com.example.aadharscanner.database.AccountDetailSyncData;
import com.example.aadharscanner.database.AddMemberAadharDetail;
import com.example.aadharscanner.database.BankBranchDetailData;
import com.example.aadharscanner.database.BankDetailData;
import com.example.aadharscanner.database.BankType;
import com.example.aadharscanner.database.BlockDaoData;
import com.example.aadharscanner.database.ChangeDesignationSyncData;
import com.example.aadharscanner.database.GpsData;
import com.example.aadharscanner.database.InactiveReasons;
import com.example.aadharscanner.database.KycDocData;
import com.example.aadharscanner.database.KycDocSyncData;
import com.example.aadharscanner.database.LoginInfoData;
import com.example.aadharscanner.database.MemberInactiveReasonData;
import com.example.aadharscanner.database.MemberLoanStatusData;
import com.example.aadharscanner.database.ShgDetailData;
import com.example.aadharscanner.database.ShgInactivationSyncData;
import com.example.aadharscanner.database.ShgInActivSyncData;
import com.example.aadharscanner.database.ShgLoanStatusData;
import com.example.aadharscanner.database.ShgMemberDetailsData;
import com.example.aadharscanner.database.ShgMemberRegistrationSyncData;
import com.example.aadharscanner.database.UpdatedDesignation;
import com.example.aadharscanner.database.VillageData;
import com.example.aadharscanner.database.WebRequestData;

import com.example.aadharscanner.database.AadharDetailSyncDataDao;
import com.example.aadharscanner.database.AccountDetailSyncDataDao;
import com.example.aadharscanner.database.AddMemberAadharDetailDao;
import com.example.aadharscanner.database.BankBranchDetailDataDao;
import com.example.aadharscanner.database.BankDetailDataDao;
import com.example.aadharscanner.database.BankTypeDao;
import com.example.aadharscanner.database.BlockDaoDataDao;
import com.example.aadharscanner.database.ChangeDesignationSyncDataDao;
import com.example.aadharscanner.database.GpsDataDao;
import com.example.aadharscanner.database.InactiveReasonsDao;
import com.example.aadharscanner.database.KycDocDataDao;
import com.example.aadharscanner.database.KycDocSyncDataDao;
import com.example.aadharscanner.database.LoginInfoDataDao;
import com.example.aadharscanner.database.MemberInactiveReasonDataDao;
import com.example.aadharscanner.database.MemberLoanStatusDataDao;
import com.example.aadharscanner.database.ShgDetailDataDao;
import com.example.aadharscanner.database.ShgInactivationSyncDataDao;
import com.example.aadharscanner.database.ShgInActivSyncDataDao;
import com.example.aadharscanner.database.ShgLoanStatusDataDao;
import com.example.aadharscanner.database.ShgMemberDetailsDataDao;
import com.example.aadharscanner.database.ShgMemberRegistrationSyncDataDao;
import com.example.aadharscanner.database.UpdatedDesignationDao;
import com.example.aadharscanner.database.VillageDataDao;
import com.example.aadharscanner.database.WebRequestDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig aadharDetailSyncDataDaoConfig;
    private final DaoConfig accountDetailSyncDataDaoConfig;
    private final DaoConfig addMemberAadharDetailDaoConfig;
    private final DaoConfig bankBranchDetailDataDaoConfig;
    private final DaoConfig bankDetailDataDaoConfig;
    private final DaoConfig bankTypeDaoConfig;
    private final DaoConfig blockDaoDataDaoConfig;
    private final DaoConfig changeDesignationSyncDataDaoConfig;
    private final DaoConfig gpsDataDaoConfig;
    private final DaoConfig inactiveReasonsDaoConfig;
    private final DaoConfig kycDocDataDaoConfig;
    private final DaoConfig kycDocSyncDataDaoConfig;
    private final DaoConfig loginInfoDataDaoConfig;
    private final DaoConfig memberInactiveReasonDataDaoConfig;
    private final DaoConfig memberLoanStatusDataDaoConfig;
    private final DaoConfig shgDetailDataDaoConfig;
    private final DaoConfig shgInactivationSyncDataDaoConfig;
    private final DaoConfig shgInActivSyncDataDaoConfig;
    private final DaoConfig shgLoanStatusDataDaoConfig;
    private final DaoConfig shgMemberDetailsDataDaoConfig;
    private final DaoConfig shgMemberRegistrationSyncDataDaoConfig;
    private final DaoConfig updatedDesignationDaoConfig;
    private final DaoConfig villageDataDaoConfig;
    private final DaoConfig webRequestDataDaoConfig;

    private final AadharDetailSyncDataDao aadharDetailSyncDataDao;
    private final AccountDetailSyncDataDao accountDetailSyncDataDao;
    private final AddMemberAadharDetailDao addMemberAadharDetailDao;
    private final BankBranchDetailDataDao bankBranchDetailDataDao;
    private final BankDetailDataDao bankDetailDataDao;
    private final BankTypeDao bankTypeDao;
    private final BlockDaoDataDao blockDaoDataDao;
    private final ChangeDesignationSyncDataDao changeDesignationSyncDataDao;
    private final GpsDataDao gpsDataDao;
    private final InactiveReasonsDao inactiveReasonsDao;
    private final KycDocDataDao kycDocDataDao;
    private final KycDocSyncDataDao kycDocSyncDataDao;
    private final LoginInfoDataDao loginInfoDataDao;
    private final MemberInactiveReasonDataDao memberInactiveReasonDataDao;
    private final MemberLoanStatusDataDao memberLoanStatusDataDao;
    private final ShgDetailDataDao shgDetailDataDao;
    private final ShgInactivationSyncDataDao shgInactivationSyncDataDao;
    private final ShgInActivSyncDataDao shgInActivSyncDataDao;
    private final ShgLoanStatusDataDao shgLoanStatusDataDao;
    private final ShgMemberDetailsDataDao shgMemberDetailsDataDao;
    private final ShgMemberRegistrationSyncDataDao shgMemberRegistrationSyncDataDao;
    private final UpdatedDesignationDao updatedDesignationDao;
    private final VillageDataDao villageDataDao;
    private final WebRequestDataDao webRequestDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        aadharDetailSyncDataDaoConfig = daoConfigMap.get(AadharDetailSyncDataDao.class).clone();
        aadharDetailSyncDataDaoConfig.initIdentityScope(type);

        accountDetailSyncDataDaoConfig = daoConfigMap.get(AccountDetailSyncDataDao.class).clone();
        accountDetailSyncDataDaoConfig.initIdentityScope(type);

        addMemberAadharDetailDaoConfig = daoConfigMap.get(AddMemberAadharDetailDao.class).clone();
        addMemberAadharDetailDaoConfig.initIdentityScope(type);

        bankBranchDetailDataDaoConfig = daoConfigMap.get(BankBranchDetailDataDao.class).clone();
        bankBranchDetailDataDaoConfig.initIdentityScope(type);

        bankDetailDataDaoConfig = daoConfigMap.get(BankDetailDataDao.class).clone();
        bankDetailDataDaoConfig.initIdentityScope(type);

        bankTypeDaoConfig = daoConfigMap.get(BankTypeDao.class).clone();
        bankTypeDaoConfig.initIdentityScope(type);

        blockDaoDataDaoConfig = daoConfigMap.get(BlockDaoDataDao.class).clone();
        blockDaoDataDaoConfig.initIdentityScope(type);

        changeDesignationSyncDataDaoConfig = daoConfigMap.get(ChangeDesignationSyncDataDao.class).clone();
        changeDesignationSyncDataDaoConfig.initIdentityScope(type);

        gpsDataDaoConfig = daoConfigMap.get(GpsDataDao.class).clone();
        gpsDataDaoConfig.initIdentityScope(type);

        inactiveReasonsDaoConfig = daoConfigMap.get(InactiveReasonsDao.class).clone();
        inactiveReasonsDaoConfig.initIdentityScope(type);

        kycDocDataDaoConfig = daoConfigMap.get(KycDocDataDao.class).clone();
        kycDocDataDaoConfig.initIdentityScope(type);

        kycDocSyncDataDaoConfig = daoConfigMap.get(KycDocSyncDataDao.class).clone();
        kycDocSyncDataDaoConfig.initIdentityScope(type);

        loginInfoDataDaoConfig = daoConfigMap.get(LoginInfoDataDao.class).clone();
        loginInfoDataDaoConfig.initIdentityScope(type);

        memberInactiveReasonDataDaoConfig = daoConfigMap.get(MemberInactiveReasonDataDao.class).clone();
        memberInactiveReasonDataDaoConfig.initIdentityScope(type);

        memberLoanStatusDataDaoConfig = daoConfigMap.get(MemberLoanStatusDataDao.class).clone();
        memberLoanStatusDataDaoConfig.initIdentityScope(type);

        shgDetailDataDaoConfig = daoConfigMap.get(ShgDetailDataDao.class).clone();
        shgDetailDataDaoConfig.initIdentityScope(type);

        shgInactivationSyncDataDaoConfig = daoConfigMap.get(ShgInactivationSyncDataDao.class).clone();
        shgInactivationSyncDataDaoConfig.initIdentityScope(type);

        shgInActivSyncDataDaoConfig = daoConfigMap.get(ShgInActivSyncDataDao.class).clone();
        shgInActivSyncDataDaoConfig.initIdentityScope(type);

        shgLoanStatusDataDaoConfig = daoConfigMap.get(ShgLoanStatusDataDao.class).clone();
        shgLoanStatusDataDaoConfig.initIdentityScope(type);

        shgMemberDetailsDataDaoConfig = daoConfigMap.get(ShgMemberDetailsDataDao.class).clone();
        shgMemberDetailsDataDaoConfig.initIdentityScope(type);

        shgMemberRegistrationSyncDataDaoConfig = daoConfigMap.get(ShgMemberRegistrationSyncDataDao.class).clone();
        shgMemberRegistrationSyncDataDaoConfig.initIdentityScope(type);

        updatedDesignationDaoConfig = daoConfigMap.get(UpdatedDesignationDao.class).clone();
        updatedDesignationDaoConfig.initIdentityScope(type);

        villageDataDaoConfig = daoConfigMap.get(VillageDataDao.class).clone();
        villageDataDaoConfig.initIdentityScope(type);

        webRequestDataDaoConfig = daoConfigMap.get(WebRequestDataDao.class).clone();
        webRequestDataDaoConfig.initIdentityScope(type);

        aadharDetailSyncDataDao = new AadharDetailSyncDataDao(aadharDetailSyncDataDaoConfig, this);
        accountDetailSyncDataDao = new AccountDetailSyncDataDao(accountDetailSyncDataDaoConfig, this);
        addMemberAadharDetailDao = new AddMemberAadharDetailDao(addMemberAadharDetailDaoConfig, this);
        bankBranchDetailDataDao = new BankBranchDetailDataDao(bankBranchDetailDataDaoConfig, this);
        bankDetailDataDao = new BankDetailDataDao(bankDetailDataDaoConfig, this);
        bankTypeDao = new BankTypeDao(bankTypeDaoConfig, this);
        blockDaoDataDao = new BlockDaoDataDao(blockDaoDataDaoConfig, this);
        changeDesignationSyncDataDao = new ChangeDesignationSyncDataDao(changeDesignationSyncDataDaoConfig, this);
        gpsDataDao = new GpsDataDao(gpsDataDaoConfig, this);
        inactiveReasonsDao = new InactiveReasonsDao(inactiveReasonsDaoConfig, this);
        kycDocDataDao = new KycDocDataDao(kycDocDataDaoConfig, this);
        kycDocSyncDataDao = new KycDocSyncDataDao(kycDocSyncDataDaoConfig, this);
        loginInfoDataDao = new LoginInfoDataDao(loginInfoDataDaoConfig, this);
        memberInactiveReasonDataDao = new MemberInactiveReasonDataDao(memberInactiveReasonDataDaoConfig, this);
        memberLoanStatusDataDao = new MemberLoanStatusDataDao(memberLoanStatusDataDaoConfig, this);
        shgDetailDataDao = new ShgDetailDataDao(shgDetailDataDaoConfig, this);
        shgInactivationSyncDataDao = new ShgInactivationSyncDataDao(shgInactivationSyncDataDaoConfig, this);
        shgInActivSyncDataDao = new ShgInActivSyncDataDao(shgInActivSyncDataDaoConfig, this);
        shgLoanStatusDataDao = new ShgLoanStatusDataDao(shgLoanStatusDataDaoConfig, this);
        shgMemberDetailsDataDao = new ShgMemberDetailsDataDao(shgMemberDetailsDataDaoConfig, this);
        shgMemberRegistrationSyncDataDao = new ShgMemberRegistrationSyncDataDao(shgMemberRegistrationSyncDataDaoConfig, this);
        updatedDesignationDao = new UpdatedDesignationDao(updatedDesignationDaoConfig, this);
        villageDataDao = new VillageDataDao(villageDataDaoConfig, this);
        webRequestDataDao = new WebRequestDataDao(webRequestDataDaoConfig, this);

        registerDao(AadharDetailSyncData.class, aadharDetailSyncDataDao);
        registerDao(AccountDetailSyncData.class, accountDetailSyncDataDao);
        registerDao(AddMemberAadharDetail.class, addMemberAadharDetailDao);
        registerDao(BankBranchDetailData.class, bankBranchDetailDataDao);
        registerDao(BankDetailData.class, bankDetailDataDao);
        registerDao(BankType.class, bankTypeDao);
        registerDao(BlockDaoData.class, blockDaoDataDao);
        registerDao(ChangeDesignationSyncData.class, changeDesignationSyncDataDao);
        registerDao(GpsData.class, gpsDataDao);
        registerDao(InactiveReasons.class, inactiveReasonsDao);
        registerDao(KycDocData.class, kycDocDataDao);
        registerDao(KycDocSyncData.class, kycDocSyncDataDao);
        registerDao(LoginInfoData.class, loginInfoDataDao);
        registerDao(MemberInactiveReasonData.class, memberInactiveReasonDataDao);
        registerDao(MemberLoanStatusData.class, memberLoanStatusDataDao);
        registerDao(ShgDetailData.class, shgDetailDataDao);
        registerDao(ShgInactivationSyncData.class, shgInactivationSyncDataDao);
        registerDao(ShgInActivSyncData.class, shgInActivSyncDataDao);
        registerDao(ShgLoanStatusData.class, shgLoanStatusDataDao);
        registerDao(ShgMemberDetailsData.class, shgMemberDetailsDataDao);
        registerDao(ShgMemberRegistrationSyncData.class, shgMemberRegistrationSyncDataDao);
        registerDao(UpdatedDesignation.class, updatedDesignationDao);
        registerDao(VillageData.class, villageDataDao);
        registerDao(WebRequestData.class, webRequestDataDao);
    }
    
    public void clear() {
        aadharDetailSyncDataDaoConfig.clearIdentityScope();
        accountDetailSyncDataDaoConfig.clearIdentityScope();
        addMemberAadharDetailDaoConfig.clearIdentityScope();
        bankBranchDetailDataDaoConfig.clearIdentityScope();
        bankDetailDataDaoConfig.clearIdentityScope();
        bankTypeDaoConfig.clearIdentityScope();
        blockDaoDataDaoConfig.clearIdentityScope();
        changeDesignationSyncDataDaoConfig.clearIdentityScope();
        gpsDataDaoConfig.clearIdentityScope();
        inactiveReasonsDaoConfig.clearIdentityScope();
        kycDocDataDaoConfig.clearIdentityScope();
        kycDocSyncDataDaoConfig.clearIdentityScope();
        loginInfoDataDaoConfig.clearIdentityScope();
        memberInactiveReasonDataDaoConfig.clearIdentityScope();
        memberLoanStatusDataDaoConfig.clearIdentityScope();
        shgDetailDataDaoConfig.clearIdentityScope();
        shgInactivationSyncDataDaoConfig.clearIdentityScope();
        shgInActivSyncDataDaoConfig.clearIdentityScope();
        shgLoanStatusDataDaoConfig.clearIdentityScope();
        shgMemberDetailsDataDaoConfig.clearIdentityScope();
        shgMemberRegistrationSyncDataDaoConfig.clearIdentityScope();
        updatedDesignationDaoConfig.clearIdentityScope();
        villageDataDaoConfig.clearIdentityScope();
        webRequestDataDaoConfig.clearIdentityScope();
    }

    public AadharDetailSyncDataDao getAadharDetailSyncDataDao() {
        return aadharDetailSyncDataDao;
    }

    public AccountDetailSyncDataDao getAccountDetailSyncDataDao() {
        return accountDetailSyncDataDao;
    }

    public AddMemberAadharDetailDao getAddMemberAadharDetailDao() {
        return addMemberAadharDetailDao;
    }

    public BankBranchDetailDataDao getBankBranchDetailDataDao() {
        return bankBranchDetailDataDao;
    }

    public BankDetailDataDao getBankDetailDataDao() {
        return bankDetailDataDao;
    }

    public BankTypeDao getBankTypeDao() {
        return bankTypeDao;
    }

    public BlockDaoDataDao getBlockDaoDataDao() {
        return blockDaoDataDao;
    }

    public ChangeDesignationSyncDataDao getChangeDesignationSyncDataDao() {
        return changeDesignationSyncDataDao;
    }

    public GpsDataDao getGpsDataDao() {
        return gpsDataDao;
    }

    public InactiveReasonsDao getInactiveReasonsDao() {
        return inactiveReasonsDao;
    }

    public KycDocDataDao getKycDocDataDao() {
        return kycDocDataDao;
    }

    public KycDocSyncDataDao getKycDocSyncDataDao() {
        return kycDocSyncDataDao;
    }

    public LoginInfoDataDao getLoginInfoDataDao() {
        return loginInfoDataDao;
    }

    public MemberInactiveReasonDataDao getMemberInactiveReasonDataDao() {
        return memberInactiveReasonDataDao;
    }

    public MemberLoanStatusDataDao getMemberLoanStatusDataDao() {
        return memberLoanStatusDataDao;
    }

    public ShgDetailDataDao getShgDetailDataDao() {
        return shgDetailDataDao;
    }

    public ShgInactivationSyncDataDao getShgInactivationSyncDataDao() {
        return shgInactivationSyncDataDao;
    }

    public ShgInActivSyncDataDao getShgInActivSyncDataDao() {
        return shgInActivSyncDataDao;
    }

    public ShgLoanStatusDataDao getShgLoanStatusDataDao() {
        return shgLoanStatusDataDao;
    }

    public ShgMemberDetailsDataDao getShgMemberDetailsDataDao() {
        return shgMemberDetailsDataDao;
    }

    public ShgMemberRegistrationSyncDataDao getShgMemberRegistrationSyncDataDao() {
        return shgMemberRegistrationSyncDataDao;
    }

    public UpdatedDesignationDao getUpdatedDesignationDao() {
        return updatedDesignationDao;
    }

    public VillageDataDao getVillageDataDao() {
        return villageDataDao;
    }

    public WebRequestDataDao getWebRequestDataDao() {
        return webRequestDataDao;
    }

}
