package com.example.aadharscanner.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MEMBER_INACTIVE_REASON_DATA".
*/
public class MemberInactiveReasonDataDao extends AbstractDao<MemberInactiveReasonData, Void> {

    public static final String TABLENAME = "MEMBER_INACTIVE_REASON_DATA";

    /**
     * Properties of entity MemberInactiveReasonData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ReasonId = new Property(0, String.class, "reasonId", false, "REASON_ID");
        public final static Property Reason = new Property(1, String.class, "reason", false, "REASON");
    }


    public MemberInactiveReasonDataDao(DaoConfig config) {
        super(config);
    }
    
    public MemberInactiveReasonDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MEMBER_INACTIVE_REASON_DATA\" (" + //
                "\"REASON_ID\" TEXT," + // 0: reasonId
                "\"REASON\" TEXT);"); // 1: reason
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MEMBER_INACTIVE_REASON_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MemberInactiveReasonData entity) {
        stmt.clearBindings();
 
        String reasonId = entity.getReasonId();
        if (reasonId != null) {
            stmt.bindString(1, reasonId);
        }
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(2, reason);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MemberInactiveReasonData entity) {
        stmt.clearBindings();
 
        String reasonId = entity.getReasonId();
        if (reasonId != null) {
            stmt.bindString(1, reasonId);
        }
 
        String reason = entity.getReason();
        if (reason != null) {
            stmt.bindString(2, reason);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public MemberInactiveReasonData readEntity(Cursor cursor, int offset) {
        MemberInactiveReasonData entity = new MemberInactiveReasonData( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // reasonId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // reason
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MemberInactiveReasonData entity, int offset) {
        entity.setReasonId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setReason(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(MemberInactiveReasonData entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(MemberInactiveReasonData entity) {
        return null;
    }

    @Override
    public boolean hasKey(MemberInactiveReasonData entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
