package com.example.aadharscanner.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SHG_INACTIVATION_SYNC_DATA".
*/
public class ShgInactivationSyncDataDao extends AbstractDao<ShgInactivationSyncData, Long> {

    public static final String TABLENAME = "SHG_INACTIVATION_SYNC_DATA";

    /**
     * Properties of entity ShgInactivationSyncData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ShgCode = new Property(1, String.class, "shgCode", false, "SHG_CODE");
        public final static Property VillageCode = new Property(2, String.class, "villageCode", false, "VILLAGE_CODE");
        public final static Property ReasonId = new Property(3, String.class, "reasonId", false, "REASON_ID");
        public final static Property LoanStatusId = new Property(4, String.class, "loanStatusId", false, "LOAN_STATUS_ID");
        public final static Property SyncStatus = new Property(5, String.class, "syncStatus", false, "SYNC_STATUS");
    }


    public ShgInactivationSyncDataDao(DaoConfig config) {
        super(config);
    }
    
    public ShgInactivationSyncDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SHG_INACTIVATION_SYNC_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SHG_CODE\" TEXT," + // 1: shgCode
                "\"VILLAGE_CODE\" TEXT," + // 2: villageCode
                "\"REASON_ID\" TEXT," + // 3: reasonId
                "\"LOAN_STATUS_ID\" TEXT," + // 4: loanStatusId
                "\"SYNC_STATUS\" TEXT);"); // 5: syncStatus
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SHG_INACTIVATION_SYNC_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ShgInactivationSyncData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(2, shgCode);
        }
 
        String villageCode = entity.getVillageCode();
        if (villageCode != null) {
            stmt.bindString(3, villageCode);
        }
 
        String reasonId = entity.getReasonId();
        if (reasonId != null) {
            stmt.bindString(4, reasonId);
        }
 
        String loanStatusId = entity.getLoanStatusId();
        if (loanStatusId != null) {
            stmt.bindString(5, loanStatusId);
        }
 
        String syncStatus = entity.getSyncStatus();
        if (syncStatus != null) {
            stmt.bindString(6, syncStatus);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ShgInactivationSyncData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String shgCode = entity.getShgCode();
        if (shgCode != null) {
            stmt.bindString(2, shgCode);
        }
 
        String villageCode = entity.getVillageCode();
        if (villageCode != null) {
            stmt.bindString(3, villageCode);
        }
 
        String reasonId = entity.getReasonId();
        if (reasonId != null) {
            stmt.bindString(4, reasonId);
        }
 
        String loanStatusId = entity.getLoanStatusId();
        if (loanStatusId != null) {
            stmt.bindString(5, loanStatusId);
        }
 
        String syncStatus = entity.getSyncStatus();
        if (syncStatus != null) {
            stmt.bindString(6, syncStatus);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ShgInactivationSyncData readEntity(Cursor cursor, int offset) {
        ShgInactivationSyncData entity = new ShgInactivationSyncData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // shgCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // villageCode
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // reasonId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // loanStatusId
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // syncStatus
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ShgInactivationSyncData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShgCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setVillageCode(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setReasonId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setLoanStatusId(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSyncStatus(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ShgInactivationSyncData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ShgInactivationSyncData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ShgInactivationSyncData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
